baseURL = 'https://vita-spire.com/'
languageCode = 'en-us'
title = 'Vita Spire'
theme = 'ananke'

[params]
  description = "Vita Spire"
  author = "Vita Spire"
  address = "20 Bay Street, 11th Floor<br>Toronto, ON M5J 2N8<br>Canada"
  email = "info@vita-spire.com"
  phone = "+1 605 585 4565"

  [[params.social]]
    name = "Facebook"
    icon = "facebook-f"
    url = "https://www.facebook.com/share/1Dm3zLDZME/?mibextid=wwXIfr"
  
  [[params.social]]
    name = "X (Twitter)"
    icon = "twitter"
    url = "https://x.com/VitaSpireInc"
  
  [[params.social]]
    name = "LinkedIn"
    icon = "linkedin-in"
    url = "https://www.linkedin.com/company/vita-spire-inc/"
  
  [[params.social]]
    name = "WhatsApp"
    icon = "whatsapp"
    url = "https://wa.me/message/TT4HUXYIDVLGC1"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 5

[[menu.main]]
  name = "About Us"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "Biomedical & Health Materials"
  url = "/products/biomedical-health-materials/"
  weight = 20

[[menu.main]]
  name = "Human Nutrition Solutions"
  url = "/products/human-nutrition-solutions/"
  weight = 25

[[menu.main]]
  name = "Advanced Industrial Materials"
  url = "/products/advanced-industrial-materials/"
  weight = 30

[[menu.main]]
  name = "Marketing Materials"
  url = "/marketing-materials/"
  weight = 35

[[menu.main]]
  name = "Contact Us"
  url = "/contact/"
  weight = 40

[[menu.footer]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.footer]]
  name = "Products"
  url = "/products"
  weight = 2

[[menu.footer]]
  name = "About"
  url = "/about"
  weight = 3

[[menu.footer]]
  name = "Contact"
  url = "/contact"
  weight = 4

[outputs]
  home = ["HTML", "JSON", "RSS"]
  section = ["HTML", "RSS"]

[outputFormats.JSON]
  mediaType = "application/json"
  baseName = "index"
  isPlainText = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
